### ISSUE TITLE
Assembly para microcontroladores

### ISSUE THREAD

**Issue by jonas4040** [andreluispy/assembly4noobs#4]
Alguma ideia de fontes boas para aprender assembly para microcontroladores sem ser no Arduino?

**Comment by andreluispy** [comment]
Eae, tudo beleza?

Com "sem ser no Arduino", você quer dizer, sem usar a linguagem do Arduino IDE? Ou se refere a microcontroladores, além do arduino, que possam ser programados em Assembly?

**Comment by jonas4040** [comment]
Me refiro não somente a microcontroladores, além do arduino, que possam ser programados em Assembly, mas também onde achar fontes boas para aprender e começar a desenvolver em assembly para microcontroladores e afins.

**Comment by andreluispy** [comment]
Nunca mexi com Assembly para microcontroladores, mas pelo que lembre, os mais usados são: MIPS e PIC.

Sobre fontes, esses dois tipos de Assembly, em especial, tem muitos conteúdos. Você pode achar conteúdos no YouTube e pesquisando no Google, você acha vários materiais fornecidos por universidades.

Espero ter ajudado ;)
